export const receitas = [
        
    {id: 1, 
    titulo: "Arroz com ovo", 
    tempoPreparo: 25, 
    porcoes: 2, 
    imagem:"/roscovo.png", 
    capaImg: "/capa/capa.png",
    descricao: "Imagem de um prato de arroz com ovo", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},

    {id: 2, 
    titulo: "Ovo com arroz e pepino", 
    tempoPreparo: "20", 
    porcoes: "1", 
    imagem: "/roscopepino.png",
    capaImg: "/capa/capa.png", 
    descricao: "Imagem de um prato de arroz com ovo", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},

    {id: 3, 
    titulo: "Ovo de codorna", 
    tempoPreparo:25, 
    porcoes: 2, 
    imagem: "/codorna.png",
    capaImg: "/capa/capa.png", 
    descricao: "Imagem de ovos de codorna em um prato", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},

    {id: 4, 
    titulo: "Ovo com macarrão e legumes", 
    tempoPreparo:25, 
    porcoes: "2", 
    imagem: "/ovomac.png", 
    descricao: "Imagem de um prato de ovos com macarrão e legumes",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "}, 

    {id: 6, 
    titulo: "Ovo com legumes", 
    tempoPreparo:25, 
    porcoes: 2, 
    imagem: "/ovoric.png",
    capaImg: "/capa/capa.png", 
    descricao: "Imagem de ovos com ricota, vagem e tomate cereja",
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},

    {id: 5, 
    titulo: "Ovo com farofa", 
    tempoPreparo:25, 
    porcoes: 2, 
    imagem: "/ovofar.png", 
    descricao: "Imagem de um prato de ovos com farofa, pepino, tomate e cogumelo", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},

    {id: 8, 
    titulo: "Ovo com pão e ricota", 
    tempoPreparo:25, 
    porcoes: 2, 
    imagem: "/ovopaoric.png",
    capaImg: "/capa/capa.png", 
    descricao: "Imagem de ovo cozido com pão e ricota", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},

    {id: 7, 
    titulo: "Ovo com guacamole", 
    tempoPreparo:25, 
    porcoes: 2, 
    imagem: "/ovopao.png",
    capaImg: "/capa/capa.png", 
    descricao: "Imagem de ovo em um pão com guacamole", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},
    
    {id: 9, 
    titulo: "Ovo com pão e guacamole", 
    tempoPreparo:25, 
    porcoes: 2, 
    imagem: "/ovoguac.png",
    capaImg: "/capa/capa.png", 
    descricao: "Imagem de ovo cozido com pão e guacamole", 
    ingredientes: "Ovos Arroz Pepino Sal Alho",
    preparo1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque ut tortor eget facilisis. Proin et enim a turpis feugiat placerat. Cras varius rutrum tortor, et auctor magna sodales sit amet. Aliquam erat volutpat. Aenean luctus eros ex. Duis accumsan justo at eros tempor iaculis. Nunc accumsan ultrices odio nec egestas. Aenean non nisi id ligula sollicitudin viverra a sit amet justo. Fusce rhoncus ligula nec libero mollis vehicula. In augue nunc, finibus et magna euismod, porta maximus sapien. Mauris aliquet vehicula porta",
    preparo2: "Maecenas ut nulla orci. Duis at vulputate lacus. Nulla tincidunt congue felis, tristique varius felis maximus ut. Cras commodo ullamcorper rhoncus. Integer lacinia tellus ut lacus pellentesque hendrerit. Maecenas eget pretium ligula. Fusce vel scelerisque diam.",
    preparo3: "Vestibulum aliquet luctus erat, eu sollicitudin urna suscipit a. Quisque condimentum tristique dolor sed sagittis. Vivamus ut semper orci, quis sodales orci. Morbi ac lorem varius ante venenatis volutpat. Nulla rhoncus nunc sed sem convallis, id finibus dolor pellentesque. In faucibus nibh eu massa feugiat, a vestibulum nisl volutpat. Suspendisse luctus id eros vitae condimentum. Sed fermentum erat eget ante viverra, nec laoreet nibh commodo. Donec sit amet aliquet velit "},   
]

